<?php

namespace Resume\ResumeBundle\Repository;

/**
 * ResumeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResumeRepository extends \Doctrine\ORM\EntityRepository
{
}
